### ISSUE TITLE
copyFile chart.js/dist/Chart.js failed

### ISSUE THREAD

**Issue by dmpvost** [geneseframework/genese#64]
Hi,

`Error in Genese cli process : Error: ENOENT: no such file or directory, copyfile '[PROJECT]/node_modules/genese/node_modules/chart.js/dist/Chart.js' -> '[PROJECT]/node_modules/genese/genese/complexity/reports/reports-styles/Chart.js'`

Small failure in copy Path

```
./src/complexity/json-ast-to-reports/services/report/reports.service.ts
at
copyFile(`${Options.pathGeneseNodeJs}/node_modules/chart.js/dist/Chart.js`, `${Options.pathOutDir}/reports-styles/Chart.js`);
```

Project + node_modules, result on a bad path

`${Options.pathGeneseNodeJs}/node_modules/chart.js/dist/Chart.js`

**Comment by geneseframework** [comment]
Hi,

Thanks for your interest in Genese Complexity. To be able to solve your problem, we need to have some additional informations : 

* What is your OS ?
* What is your nodejs version ?
* What is your typescript version ?
* Did you installed node with nvm ?

It seems that genese is unable to find the path "${Options.pathGeneseNodeJs}/node_modules/chart.js/dist/Chart.js". We made a fix about relative or absolute paths in the 0.2.1 version which is available now, so maybe it will fix your problem too.

Could you try to install globally the new version of genese and have a try on it ?

Thanks for your reply.
